django/url_shortener/url_shortener_app/urls.py
# Second attempt
  
# from django.contrib import admin
# from django.urls import path, include


# Attempt three

# urlpatterns = patterns('',
#     url(r'^$', 'url_shortener_app.views.home'),
#     url(r'^(?P<id>[a-zA-Z0-9])$', 'url_shortener_app.views.link'),
#     url(r'^(?P<id>[a-zA-Z0-9])/stats$', 'url_shortener_app.views.stats'),


# from django.urls import path
# from . import views

# app_name= 'url_shortener_app'

# urlpatterns=[
#     path('', views.index, name='index'),
#     path('generate/', views.generate, name='generate'),
#     path('<str:code>/', views.redirect, name='redirect')

from django.urls import path

from . import views

app_name = "url_shortener_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("shorten_url/", views.shorten_url, name="shorten_url"),
    path("get_short_code/<str:transmit>/", views.get_short_code, name="get_short_code"),
    path("<str:new>/", views.redirect, name="redirect"),
]

django/url_shortener/url_shortener_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('url_shortener_app.urls')),
]

django/url_shortener/url_shortener_app/models.py
# *first attempt skeleton*

# class url_shortener_codeManager(models.Manager):
#     def all(self, *args, **kwargs):
#         nc_primary = super(url_shortener_codeManager, self).all(*args, **kwargs)
#         nc = nc.filter(active=False)
#         return nc

# Second attempt

# from django.db import models
# import string

# _char_map = string.ascii_letters+string.digits

# def index(sequence):
#     return "".join([_char_map[x] for x in sequence])

# *more robust model, try to implement if possible

# class url_shortener_code(models.Model):
#     url = models.CharField(max_length=210, )
#     shortcode = models.CharField(max_length=15, unique=True, blank = True)
#     update = models.DateTimeField(auto_now=True)
#     time = models.DateTimeField(auto_now_add=True)
#     active = models.BooleanField(default=True)
#     objects = url_shortener_codeManager()
#     # randomly = url_shortener_code()


# class Link(models.Model):
#     link = models.URLField()
#     hits = models.IntegerField(default=0)

#     def __repr__(self):
#         return "<Link (Hits %s): %s>"%(self.hits, self.link)

#     def short(self):
#         _id = self.id
#         digits = []
#         while _id > 0:
#             rem = _id % 62
#             digits.append(rem)
#             _id /= 62
#         digits.reverse()
#         return index_to_char(digits)

from django.db import models

class url(models.Model):
    code = models.URLField(max_length=6)
    long = models.URLField(max_length=100)
    clicks = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.code} : '{self.long}'"


    # @staticmethod
    # def decode(string):
    #     i = 0
    #     for c in string:
    #         i = i * 64 + _char_map.index(c)
    #     return i

# dead code, use as reference

#     def refresh(self, items=75):
#         print(items)
#         nc = url_shortener_code.objects.filter(id_get=1)
#         new = 0
#         for n in nc:
#             n.shortcode = generate_shortcode(n)
#             n.save()
#             new += 1
#         return "new codes: {i}".format(i=new)

#     def save(self, *args, **kwargs):
#         if self.shortcode is None or self.shortcode == "":
#             self.shortcode = generator()
#         super(url_shortener_code, self).save(*args, **kwargs)


#     def __str__(self):
#         return str(self.url)

class data(models.Model):
    ip = models.CharField(max_length=12, default="", editable=False) 
    agent = models.CharField(max_length=200, default="", editable=False) 
    link = models.ForeignKey(url, on_delete=models.CASCADE, default="", editable=False)
    amount = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.ip}@({self.agent}) clicked {self.link} a total of {self.amount} time(s)"

    def user_str(self):
        return f"{self.ip}@({self.agent})"

django/url_shortener/url_shortener_app/views.py
# Second attempt
# from tiny_link import models
# from django.shortcuts import render_to_response
# from django.template import RequestContext

# from django.shortcuts import redirect, get_object_or_404
# from django.db.models import F

import random
import string
from .models import url
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.db import IntegrityError
from django.urls import reverse

# def index(request):
#     return render(request, 'url_shortener_app/index.html', context=None)

def index(request):
    return render(request, "url_shortener_app/index.html")

# def home(request):
#    short_url = None
#    if request.method == "POST":
#       link_db = models.Link()
#       link_db.link = request.POST.get("url")
#       link_db.save()
#       short_url = request.build_absolute_uri(link_db.get_short_id())
#    return render_to_response("index.html",
#                              {"short_url":short_url},
#                              context_instance=RequestContext(request))

def shorten_url(request):
    lengthened=request.POST['url']
    code=''.join(random.choices(string.ascii_lowercase+string.digits, k=7))
    new=url.objects.create(code=code,long=lengthened)
    print(new)
    return render(request,'url_shortener_app/generate.html',context={'code': code})

def redirect(request, new):
    code = url.objects.get(code=new)
    code.clicks +=1
    code.save()
    # if not re.match('(?:http|https|ftp)://',code.long):
    #     return HttpResponseRedirect('http://{}'.format(code.long))
    return HttpResponseRedirect(code.long)


# def link(request, id):
#    db_id = models.Link.deocde_id(id)
#    link_db = get_object_or_404(models.Link, id=db_id)
#    models.Link.objects.filter(id=db_id).update(hits=F('hits')+1)
#    return redirect(link_db.link)


    # url_code = request.POST['url']
    # while True:  
    #     url_code= ''
    #     for i in range(6):
    #         url_code_code += random.choice(string.ascii_lowercase+string.digits)
    #     url_code = url.objects.filter(code__exact = url_code)
    #     if not url_code:  
    #         break  
    # url_code = url.objects.create(url = url_code_url, code = url_code)
    # return HttpResponseRedirect(reverse('results', args = (url_code.short,)))
    # message = {}
    # try:
    #     temp = url(long= request.POST["link"], short=new())
    #     temp.save()
    #     message["success"] = temp
    # except KeyError:
    #     message["messages"] = "Submission error"
    # except IntegrityError:
    #     message["messages"] = f"That link already exists!"
    #     message["success"] = url.objects.get(long=request.POST['link'])

def new(): 
    code = "".join([random.choice(string.ascii_letters + string.digits) for unused in range(0, 6)])
    while url.objects.filter(short=code).exists(): # must be a unique code
        code = "".join([random.choice(string.ascii_letters + string.digits) for unused in range(0, 6)])
    return 


# def generate(request):
#     code=''.join(random.choices(string.ascii_lowercase+string.digits, k=7))
#     new_url=Url(code=code,long_url=request.POST.get('url'))
#     print(new_url)
#     new_url.save()
#     return render(request,'url_shortener_app/generate.html',context={'code': code})

# def redirect(request, code):
#     found_url = get_object_or_404(Url, code=code)
#     try:
#         click= Click(ip=request.META['REMOTE_ADDR'], click_url=found_url, referral=request.META['HTTP_REFERER'])
#         click.save()
#     except:
#         click= Click(ip=request.META['REMOTE_ADDR'], click_url=found_url, referral='none')
#         click.save()
#     print(found_url.click_set.count())

#     return HttpResponseRedirect(f"{found_url}")
    
def get_short_code(request, transmit):
    link = get_object_or_404(url, short=transmit)
    users = data.objects.filter(link_clicked__exact=link).order_by("ip", "amount")
    return render(request, "url_shortener_app/get_short_code.html", context={"users": users, "link": link})

# from django.shortcuts import render

# for n in range (length) :
#         short_url += random. (characters)
#     new = ShortUrl.objects.create(short_url= ,long_url= )
#     print(new.short_url, new.id)
#     print(url_input)
#     return HttpResponseRedirect(reverse('url_shortner_app:results', args=(short_url,)))










        

django/url_shortener/url_shortener_app/templates/url_shortener_app/generate.html
{% extends "url_shortener_app/get_short_code.html" %}
{% block content %}
<p>Link below:</p>
<a class="redirect-link" href="/{{code}}/">localhost:8000/{{code}}</a><br><br>
<a class="home-link"href="/">home</a>
{% endblock content %}

django/url_shortener/url_shortener_app/templates/url_shortener_app/get_short_code.html
  
{%load static%}
<!DOCTYPE html>
    <head>
        
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel='stylesheet' href="{%static 'url_shortener_app/css/responsiveness.css'%}">
        
        <title>url shortener</title>
         

    </head>
    <body>
        <div class="jumbotron">
            <h1 class="display-4">url shortener</h1>
            <hr class="my-4">
            {% block content %}{% endblock %}
        </div>
    
        
        
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

django/url_shortener/url_shortener_app/templates/url_shortener_app/index.html
{%extends 'url_shortener_app/get_short_code.html'%}
{%block content%}
<form action= '{% url "url_shortener_app:shorten_url"%}' method='post'>
    {% csrf_token %}
    <input type="text" name="url" required>
    <input class="btn btn-primary btn-sm" type="submit" value="submit url">
</form>
{%endblock%}

{% comment %} Attempt one {% endcomment %}

{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">

    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
    <style type="text/css">
        body {
            padding-top: 60px;
            padding-bottom: 40px;
        }
    </style>
</head>

<body>
<div class="row-fluid">
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a href="/" class="brand">TinyLink</a>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="hero-unit">
            <div class="row-fluid">
                <div class="row">
                    <div class="span12">
                        <h1>Shortern a link</h1>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="span12">
                        <div class="control-group">
                            <form class="form-horizontal" id="url_submit_form" method="POST" action="/">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="span5">
                                        <div class="control-group {% if error %}error{% endif %}">
                                            <input type="text" name="url"
                                                   placeholder="http://google.com"
                                                   value="{% if url %}{{ url }}{% endif %}"
                                                   id="url_input"
                                                   class="span5">
                                            {% if error %}
                                                <span class="help-inline">Please enter a valid URL</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="span2">
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    {% if shorturl %}
                        <h2>Success!</h2>
                        <p>Shortened URL: <a href="{{ shorturl }}">{{ shorturl }}</a></p>
                        <p>View statistics: <a href="{{ shorturl }}/stats">{{ shorturl }}/stats</a></p>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html> {% endcomment %}