django/chirp/chirp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login', views.LoginView.as_view(), name='login'),
    path('accounts/leave/', views.LogoutView.as_view(), name='leave'),
    path('', include('chirp_ranters.urls')),
    path('', include('chirp_timeline.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/chirp/chirp_ranters/urls.py
from django.urls import path
from . import views

app_name = 'chirp_ranters' 
urlpatterns = [
    path('beseech/', views.beseech, name='beseech'),
    path('ranter/<str:trollavatar>/', views.details, name='details'),
]

django/chirp/chirp_timeline/urls.py
from django.urls import path
from . import views

app_name = 'chirp_timeline'
urlpatterns = [
    path('', views.ledger, name='ledger'),
    path('vestal', views.vestal, name='vestal'),
    path('<int:rant_id>/tarnish', views.tarnish, name='tarnish'),
    path('<int:rant_id>/banish', views.banish, name='banish'),
]

django/chirp/chirp_users/urls.py
from django.urls import path
from . import views

app_name = 'chirp_users' 
urlpatterns = [
    path('beg', views.user_signup, name='beg'),
    path('user/<str:trollavatar>/', views.details, name='details'),
]

django/chirp/chirp_ranters/models.py
# from django.db import models

# # first attempt

# class Chirp(models.Model):
#     troll = models.ForeignKey('auth.User', on_delete=models.CASCADE)
#     spitfire = models.CharField(max_length=100)
#     incepted = models.DateTimeField(auto_now_add=True)

# class Stalk(models.Model):
#     ranter = models.ForeignKey('auth.User', on_delete=models.CASCADE)
#     target = models.ForeignKey('auth.User', on_delete=models.CASCADE)
#     created = models.DateTimeField(auto_now_add=True)

    # class Meta:
    #     unique = ('user', 'target')

django/chirp/chirp_timeline/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Rants(models.Model):

    spitfire = models.CharField(max_length=140)

    ranter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    incepted = models.DateTimeField(default=timezone.now)

    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)

    tarnished = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        
        return self.spitfire

django/chirp/chirp_ranters/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm


def beseech(beseech):
    if beseech.method == 'POST':
        form = UserCreationForm(beseech.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(beseech, 'beseech.html', {'form': form})
    
def details(beseech, trollavatar):
    ranter = get_object_or_404(User, trollavatar = trollavatar)
    spitfire = ranter.post_set.all().order_by('-incepted')
    return render(beseech, 'chirp_timeline/ledger.html', {'chirp_timeline': chirp_timeline})

# from django.shortcuts import render
# from django.contrib.auth.forms import UserCreationForm
# from django.urls import reverse_lazy
# from django.views import generic
# from django.contrib.auth.models import User
# from django.shortcuts import get_object_or_404

# class beseech(generic.CreateView):
#     form = UserCreationForm
#     template = 'beseech.html'
#     success = reverse_lazy('phish')

# class details(generic.DetailView):
#     model = User
#     template = 'details.html'

#     def get_object(self):
#         return get_object_or_404(User, username=self.kwargs['trollavatar'])

django/chirp/chirp_timeline/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.utils import timezone
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .models import Rants
from django import forms

class AffixSheet(forms.ModelForm):

    class Meta:
        model = Rants
        fields = ('spitfire', 'avatar')

def ledger(request):

    rants= Rants.objects.filter(incepted__lte=timezone.now()).order_by('-incepted')

    return render(request, 'chirp_timeline/ledger.html', {'rants': rants})


@login_required

def vestal(request):

    if request.method == 'POST':

        form = AffixSheet(request.POST, request.FILES) 

        if form.is_valid():

            spitfire = form.cleaned_data.get('spitfire')

            avatar = form.cleaned_data.get('avatar')

            ranter = request.user

            incepted = timezone.now()

            rant = Rants.objects.create(spitfire=spitfire, avatar=avatar, ranter=ranter, incepted=incepted) 

            rant.save()

            return redirect('chirp_timeline:ledger')

    else:

        form = AffixSheet()

    return render(request, 'chirp_timeline/vestal.html', {'form': form}) 


def tarnish(request, rant_id):

    ranter = request.user

    rant = get_object_or_404(Rants, pk = rant_id)

    if rant.ranter == ranter:

        if request.method == 'POST':

            form = AffixSheet(request.POST, request.FILES) 

            if form.is_valid():

                spitfire = form.cleaned_data.get('spitfire')

                avatar = form.cleaned_data.get('avatar')

                rant.spitfire = spitfire

                rant.avatar = avatar

                rant.tarnish = timezone.now()

                rant.save()

                return redirect('chirp_timeline:ledger')

        else:

            form = AffixSheet()

        return render(request, 'chirp_timeline/tarnish.html', {'form': form}) 

    return HttpResponseForbidden('403 Forbidden')

def banish(request, rant_id):

    ranter = request.user

    rant = get_object_or_404(Rants, pk = rant_id)

    if rant.ranter == ranter:

        rant.delete()

        return HttpResponseRedirect(reverse('chirp_timeline:ledger'))
        
    return HttpResponseForbidden('403 Forbidden')

django/chirp/chirp_ranters/templates/beseech.html
{% extends 'chirp_timeline/foundation.html' %}

{% block content %}
    <h2>Beseech: </h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="sign up">
        </form>
{% endblock content %}

django/chirp/chirp_timeline/templates/beg/phish.html
{% extends "posts/base.html" %}

{% block content %}
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'login' %}">
    {% csrf_token %}
        <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
        </table>

        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
{% endblock %}

django/chirp/chirp_timeline/templates/chirp_timeline/foundation.html
{% load static %}


{% comment %} Reference {% endcomment %}
{% comment %} <html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <title>Stream Twitter</title>
      <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
      <meta http-equiv="cleartype" content="on">
      <link href="https://fonts.googleapis.com/css?family=Raleway:400,700,200" rel="stylesheet" type="text/css">
      <link href="/static/css/bootstrap.min.css" rel="stylesheet">
      <link rel="stylesheet" href="/static/css/style.css" type="text/css">
      <link rel="stylesheet" href="/static/css/stream_twitter.css" type="text/css">
  </head>
<body>
    {% block nav %}
      {% include "stream_twitter/_nav.html" %}
    {% endblock nav %}
    {% block content %}
    {% endblock content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    {% block script %}
    {% endblock script %}
</body> {% endcomment %}

<html>

    <head>

        <title>Chirp</title>

        <link rel="stylesheet" href="{% static 'css/chirp_timeline.css' %}"> 

        <style>

        body {
            font-family: 'Evogria';
            padding: 20px;
            background: black;
            color: red;
            background-image: url("/Users/pizzaboynizza/PycharmProjects/class_whatever/code/Justin/django/chirp/chirp_timeline/static/css/photo-1517594422361-5eeb8ae275a9.jpeg");
            }
        </style>

    </head> 

    <div class="header">

        {% if user.is_authenticated %}

            <p class="top">Ohayou {{ user.username }} <small>(<a href="{% url 'leave' %}">Leave</a>)</small></p>

        {% else %}

            <a href="{% url 'login' %}" class="top">Phish</a>

            <a href="{% url 'chirp_ranters:beseech' %}"  class="top">Beseech</a>

        {% endif %}

        <h1><a href="{% url 'chirp_timeline:vestal' %}">Rant</a></h1>

    </div>

    <div class="content container">

        <div class="row">

            <div class="col-md-8">

            {% block content %}

            {% endblock %}

            </div>

        </div>

    </div class="footer">

        <a href="{% url 'chirp_timeline:ledger' %}"><h1>Back!</h1></a>

    </div>

</body>

</html> 




    
   

django/chirp/chirp_timeline/templates/chirp_timeline/ledger.html
{% extends 'chirp_timeline/foundation.html' %} 

{% block content %}

    {% for rant in rants %}

        <div class="rant">

            <div class="date">

                <p>ranter: <a href="{% url 'chirp_ranters:details' rant.ranter.username %}">{{ post.author }}</a></p>

                <p>incepted: {{ rant.incepted }}</p>

                {% if rant.tarnished %}

                    <p>tarnished: {{ rant.tarnished }}</p>   

                {% endif %}

            </div>

            {% if rant.ranter == user %}

                <a href="{% url 'chirp_timeline:tarnish' rant.pk%}">tarnish</a>

                <a href="{% url 'chirp_timeline:banish' rant.pk%}">banish</a>

            {% endif %}

            <p>{{ rant.spitfire|linebreaksbr }}</p>

            {% if rant.avatar %}

                <img height=Auto, width=Auto, src="{{rant.avatar.url}}">

            {% endif %}

        </div>

    {% endfor %}
    
{% endblock %} 

django/chirp/chirp_timeline/templates/chirp_timeline/tarnish.html
{% extends 'chirp_timeline/foundation.html' %}

{% comment %} //template {% endcomment %}
{% comment %} {% block content %}
    <h2>Beseech: </h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="sign up">
        </form>
{% endblock content %} {% endcomment %}

{% block content %}

    <h2>Tarnish</h2>

    <form method="POST" class="form" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="save btn btn-default">Save</button>

    </form>
    
{% endblock %}

django/chirp/chirp_timeline/templates/chirp_timeline/vestal.html
{% extends 'chirp_timeline/foundation.html' %}

{% comment %} //template {% endcomment %}
{% comment %} {% block content %}
    <h2>Beseech: </h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="sign up">
        </form>
{% endblock content %} {% endcomment %}

{% block content %}

    <h2>Rant</h2>

    <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="save btn btn-default">Save</button>

    </form>
    
{% endblock %}

django/chirp/chirp_timeline/templates/rants/edit.html
{% extends 'posts/base.html' %}

{% block content %}
    <h2>Edit post</h2>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

django/chirp/chirp_timeline/templates/rants/foundation.html
{% load static %}

<html>
    <head>
        <title>Chirp</title>
        <link rel="stylesheet" href="{% static 'css/chirp_timeline.css' %}"> 
    </head> 
    <div class="page-header">
        {% if user.is_authenticated %}
            <a href="{% url 'chirp_timeline:vestal' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <p class="top-menu">Ohayou {{ ranter.trollavatar }} <small>(<a href="{% url 'leave' %}">Leave</a>)</small></p>
        {% else %}
            <a href="{% url 'phish' %}" class="top-menu">Phish</a>
            <a href="{% url 'chirp_ranters:beg' %}"  class="top-menu">Beg</a>
        {% endif %}
        <h1><a href="{% url 'chirp_timeline:ledger' %}">Chirp</a></h1>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div class="page-footer">
        <a href=""><h1>Back to top</h1></a>
    </div>
</body>
</html>

django/chirp/chirp_timeline/templates/rants/ledger.html
{% extends 'rants/foundation.html' %}

{% block content %}
    {% for rant in rants %}
        <div class="rant">
            <div class="date">
                <p>ranter: <a href="{% url 'ranters:detail' rant.ranter.trollavatar %}">{{ post.author }}</a></p>
                <p>incepted: {{ rant.incepted }}</p>
                {% if rant.tarnished %}
                    <p>tarnished: {{ rant.tarnished }}</p>            
                {% endif %}
            </div>
            {% if rant.ranter == user %}
                <a href="{% url 'rants:tarnish' rant.pk%}">tarnish</a>
                <a href="{% url 'rants:banish' rant.pk%}">banish</a>
            {% endif %}
            <p>{{ rant.spitfire|linebreaksbr }}</p>
            {% if rant.avatar %}
                <img height=Auto, width=Auto, src="{{rant.avatar.url}}">
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}

django/chirp/chirp_timeline/templates/rants/tarnish.html
{% extends 'rants/foundation.html' %}

{% block content %}
    <h2>Tarnish</h2>
    <form method="POST" class="rant-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

django/chirp/chirp_timeline/templates/rants/vestal.html
{% extends 'rants/foundation.html' %}

{% block content %}
    <h2>Rant</h2>
    <form method="POST" class="rant-form" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

django/chirp/chirp_users/templates/beseech.html
{% extends 'posts/base.html' %}

{% block content %}
    <h2>Beseech us:</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}