django/grocery_list/grocery_list/urls.py
from django.urls import path
from . import views

app_name = 'grocery_list'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('detail/', views.detail, name='detail'),
    path('delete/<int:grocery_item_id>', views.delete, name='delete'),
    path('incomplete/', views.incomplete, name='incomplete'),
    path('complete/<int:grocery_item_id>', views.complete, name='complete'),
]

django/grocery_list/groceryproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('groceryapp.urls'))
]

handler404 = 'groceryapp.views.handler404'
handler500 = 'groceryapp.views.handler500'

django/grocery_list/grocery_list/models.py
from django.db import models
from django.utils import timezone

class GroceryItem(models.Model):
    item_text = models.CharField(max_length = 200)
    created_date = models.DateTimeField(default=timezone.now)
    completed_date = models.DateTimeField(blank=True, null=True)
    was_completed = models.BooleanField(default=False)

    def complete(self):
        self.completed_date = timezone.now()
        self.was_completed = True
        self.save()

    def incomplete(self):
        self.completed_date = None
        self.was_completed = False
        self.save()

    def __str__(self):
        return self.item_text

django/grocery_list/grocery_list/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone

from .models import GroceryItem

def index(request):
    context = {
        'incomplete_items':GroceryItem.objects.filter(was_completed=False).order_by('created_date'),
        'completed_items':GroceryItem.objects.filter(was_completed=True).order_by('completed_date'),
    }
    return render(request, 'grocery_list/index.html', context)

def create(request):
    grocery_item_text = request.POST['item']
    GroceryItem.objects.create(item_text = grocery_item_text, created_date = timezone.now())
    return HttpResponseRedirect(reverse('grocery_list:index'))

def detail(request, grocery_item_id):
    grocery_item = get_object_or_404(GroceryItem, pk = grocery_item_id)
    return render(request, "grocery_list/detail.html", {"grocery_item": grocery_item})

def incomplete(request, grocery_item_id):
    grocery_item = get_object_or_404(GroceryItem, pk = grocery_item_id)
    grocery_item.incomplete()
    grocery_item.save()
    return HttpResponseRedirect(reverse('grocery_list:index'))

def complete(request, grocery_item_id):
    grocery_item = get_object_or_404(GroceryItem, pk = grocery_item_id)
    grocery_item.was_completed=True
    grocery_item.completed_date=timezone.now()
    grocery_item.save()
    return HttpResponseRedirect(reverse('grocery_list:index'))

def delete(request, grocery_item_id):
    grocery_item = get_object_or_404(GroceryItem, pk = grocery_item_id)
    grocery_item.delete()
    return HttpResponseRedirect(reverse('grocery_list:index'))

django/grocery_list/grocery_list/templates/grocery_list/index.html
<h1>Shopping List</h1>

         <div class="box">
                <h2>Add an item to the list</h2>
                <form action="{% url 'grocery_list:create' %}" method="post">
                    {% csrf_token %}
                    <input type="text" name="item" id="item" required/>
                    <label for="item">Add an Item</label><br/>
                    <input type="submit" value="Add to List"/>
                    {% if error %}
                        <p class="error">{{ error }}</p>
                    {% endif %}
                </form>
    <h2>Incomplete items</h2>
    {% csrf_token %}
    {% if incomplete_items %}
        <ul>
        {% for item in incomplete_items %}
            <li>{{item.item_text}}</li>
            <a href="{% url 'grocery_list:complete' item.id %}">Completed this item</a>
        {% endfor %}

        </ul>

    {% else %}
        <p>Nothing to see here!</p>

    {% endif %}

    <h2>Completed items</h2>

    {% csrf_token %}
    {% if completed_items %}
        <ul>
        {% for item in completed_items %}
            <li>{{item.item_text}}</li>
            <a href="{% url 'grocery_list:delete' item.id %}">Delete this item</a>
        {% endfor %}

        </ul>

    {% else %}
        <p>Nothing to see here!</p>

    {% endif %}


{% comment %} <form action= '{% url "delete" %}' method='post'>
    {% csrf_token %}
    <input type="submit" value="remove completed items">
</form> {% endcomment %}